<html>

<h2>Basic Exception Handling</h2>
<p>Uncaught exceptions will terminate execution of your application.</p>
<p>Basic principles of catching possible known exceptions apply whether running in, or outside, of a coroutine.</p>

<br>
<h3>💡 Helpful Resources</h3>
<ul>
    <li> <a href="https://kotlinlang.org/docs/exception-handling.html">Exception Handling</a> </li>
</ul>

<br>
<h3>📝 Instructions</h3>
<p>Wrap the thrown exception in a try/catch to allow the launched coroutines to complete.</p>

<br>
<h3>🤔 Observations</h3>
<ul>
    <li>What do you think would happen if an exception was thrown from within one of the <em>launch{}</em> calls?</li>
</ul>
</html>